<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OOQID91" failures="1" tests="3" name="Selenium.FinalAssignment.TestRunner" time="0.126" errors="0" timestamp="2024-04-13T20:29:50 IST" skipped="0">
  <testcase classname="Selenium.FinalAssignment.TestRunner" name="runScenario" time="0.002"/>
  <testcase classname="Selenium.FinalAssignment.TestRunner" name="runScenario" time="0.004"/>
  <testcase classname="Selenium.FinalAssignment.TestRunner" name="runScenario" time="0.120">
    <failure message="expected [PRIME] but found [ODD]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [PRIME] but found [ODD]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepDefinition.main.verify_odd_result(main.java:29)
at âœ½.The result is ODD(file:///D:/eclipseAssignment/FinalAssignment/src/test/java/features/feature.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Selenium.FinalAssignment.TestRunner -->
